services:
    frontend:
        restart: always
        build: 
            dockerfile: Dockerfile
            context: ./frontend 
        ports:
            - '8000:8000'
    backend:
        restart: always
        build: 
          dockerfile: Dockerfile
          context: ./backend
        ports: 
          - '8080:8080'
