services:
    frontend:
        restart: always
        build: 
            dockerfile: Dockerfile
            context: ./frontend 
        ports:
            - '8090:8090'
    backend:
        restart: always
        build: 
          dockerfile: Dockerfile
          context: ./backend
        ports: 
          - '8085:8085'
